# -*- coding: utf-8 -*-
"""3/13Next.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NCiXXP7C6vu4tY5IZpaqnskAV1ZC-mRg
"""

import random
def RCP():
  print("==============Restart=============")
  idx = ["가위", "바위", "보"]
  you = input("가위 바위 보! :")
  com = random.choice(idx)
  print(f"컴퓨터는 {com}")
  if you == com:
    print("비겼습니다.")
  elif (you, com) in [("가위", "바위"), ("바위", "보"), ("보", "가위")]:
    print("컴퓨터가 이겼네요.")
  else:
    print("니가 이겼구나")

RCP()

def talking(n):
  if n == "고양이":
    print("야옹")
  elif n == "김지욱":
    print("안녕하세요. 만나서 반갑습니다.")
  else:
    print(f"나는 {n}가 아니라 알락꼬리꼬마도요야")


N = input()
talking(N)

def start():
  for i in range(10, 0, -1):
    print("발사")
    print(i)
start()

def start():
  cnt = 10
  while True:
    print("발사")
    print(cnt)
    if cnt == 1:
      break
    cnt -= 1
start()

class Bank():
  account = 1000
  limit_for_loan = 500
  limit_for_withdraw = 100

  def withdraw_money(self, amount):
    count = amount // self.limit_for_withdraw
    rest = amount % self.limit_for_withdraw
    for i in range(count):
      print(f"This is your money - {self.limit_for_withdraw}")
    if rest != 0 :
      print(f"This is your money - {rest}")

  def give_me_money(self, amount):
    if amount <= self.account:
      self.withdraw_money(amount)
    elif amount <= (self.account + self.limit_for_loan):
      print("wait")
    else:
      print("Not enough money")

hana_bank = Bank()
sinhan_bank = Bank()
hana_bank.give_me_money(950)

