# Generated by Django 4.2 on 2023-04-12 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_innercomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='innercomment',
            old_name='post',
            new_name='comment',
        ),
    ]
