# -*- coding: utf-8 -*-
"""3/23 class 실습.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FV460kCTN9ERIVEhOiPIqpP_24urPNl-
"""

class Person:
  def __init__(self, name, age, height):
    self.name = name
    self.age = age
    self.height = height

  def yell(self):
    print("아?")
  
  def introduce(self):
    print(f"안녕하세요. 제 이름은 {self.name}이고, 나이는 {self.age}살이며, 제 키는 {self.height}")


class Developer(Person):
  keyboard = "기계식"
  def __init__(self, name, age,height):
    super().__init__(name, age, height)
  
  def yell(self):
    print("어?")
  
class Designer(Person):
  def __init__(self, name, age,height):
    super().__init__(name, age, height)
    self.disease = 0


class ProductManager(Person):
  def __init__(self, name, age,height):
    super().__init__(name, age, height)

  def yell(self):
    print("개발자님 여기 오류있어요")
  
  def aging(self):
    self.age -= 2
    self.height -= 5
    print("개발자를 새로 뽑아야 하나...")
    Developer.keyboard = "멤브레인"

d1 = Developer("이야호", 3, 100)
d2 = Designer("무야호", 5, 120)
p1 = ProductManager("유야호", 7, 140)
d1.introduce()
d1.yell()
d2.introduce()
d2.yell()
p1.introduce()
p1.yell()
p1.aging()
p1.introduce()